spring:
  application:
    name: hakase

discord:
  token: ${DISCORD_BOT_TOKEN}

sentry:
  dsn: https://803b0d97ed9756be1f531412d572f408@o4507124907638784.ingest.us.sentry.io/4509828350476288
  send-default-pii: true
  tracesSampleRate: 1.0
  profileSessionSampleRate: 1.0
  profileLifecycle: TRACE
  logs:
    enabled: true